on: [push, pull_request]

jobs:
  prepare:
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
  lint:
    needs: ['prepare']
    steps:
      - name: Execute lint
        run: |
          make lint
  tests:
    needs: ['lint']
    steps:
      - name: Test with pytest
        run: |
          pytest ycurve/tests